language: go

go:
  - 1.8
  - 1.9
  - master

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

before_script:
  - ./.scripts/lint.sh
  - ./.scripts/vet.sh

script:
  - ./.scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
