// Copyright 2017 Typeform SL. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

// Package cmd is auto generated by cobra
package cmd

import (
	"github.com/jennyservices/jenny/debug"
	"github.com/spf13/cobra"
)

// serveCmd represents the serve command
var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "runs a go package in debug mode",
	Long: `Runs a debug package in debug mode.
	Serve assumes that your application will listen `,
	Run: func(cmd *cobra.Command, args []string) {
		if len(args) != 1 {
			return
		}
		debug.Start(args[0])
	},
}

func init() {
	RootCmd.AddCommand(serveCmd)
}
