---
swagger: '2.0'
info:
  version: 1.0.0
  title: Meta

paths:
  /_spec:
    get:
      tags:
        - debug
      summary: Returns a list of registered services
      operationId: specs
      produces:
        - application/json
        - application/xml
      responses:
        200:
          description: successful attempt
          schema:
              type: array
              items:
                $ref: '#/definitions/Service'
definitions:
  Service:
    properties:
      name:
        type: string
      spec:
        type: string
        format: byte
      version:
        type: string
      hash:
        type: string
        format: byte
